apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-capstone-deployment
  labels:
    app: uda-capstone
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: uda-capstone-backend
        image: brianx0215/uda-capstone:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: uda-capstone-loadbalancer
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80